### ISSUE TITLE
[REQUEST] armhf support

### ISSUE THREAD

**Issue by kamilmirza** [accetto/ubuntu-vnc-xfce-firefox-plus#1]
as the title 
can you please add **`armhf`** support? 
would really like to have minimal browser image

**Comment by accetto** [comment]
Hello kamilmirza,

thank you for you feedback. My first reaction: why not? :)
I'll try to find some time as soon as possible. However, I have to do some research first.
Therefore I can't promise it so soon.

How do you imagine an ideal image?

Regards
accetto

**Comment by kamilmirza** [comment]
thanks a lot
take your time 
ideal image will be [ubuntu](https://hub.docker.com/r/arm32v7/ubuntu/) with minimal xfce with novnc/vnc

**Comment by accetto** [comment]
Hello kamilmirza,
sorry that it takes so long ...
One question - would you need also **noVNC** and/or **nss_warpper** functionality?
accetto

**Comment by accetto** [comment]
Closing it because I'll not be able to find any time for this pretty long. Also the original requester doesn't respond any more.
