### ISSUE TITLE
Chromium NoVNC Version

### ISSUE THREAD

**Issue by duurent** [accetto/ubuntu-vnc-xfce-firefox-plus#5]
I can't get it to work with the docker run command, I just started with github and Docker so I am desperately trying to make it work.

Is is possible that you add an NoVNC version for accetto/xubuntu-vnc-chromium docker. (Since this one has sudo commands activated so there wouldn't be a need to access as root).

Or maybe you can help me in creating it for myself

The problem is that I am restricted in using a NoVNC container because of all the restriction with my connection. I need to access it over the internet.

**Comment by accetto** [comment]
I see.

Actually I'm thinking about creating xubuntu-images with noVNC, but I cannot say when I'll come to it.

I'll try to create some quick Dockerfiles with Chrome and maybe also sudo for you.
I'll let you know soon.

**Comment by duurent** [comment]
Thnx already for this information. I will keep an eye on your Github and Docker files.

**Comment by accetto** [comment]
So, I've checked it and it seems that I can release some quick solution for you.
Give me a few days.

**Comment by accetto** [comment]
After testing several combinations I've decided to go with a stand-alone repository for the ubuntu-based image with Chromium. The images and Dockerfiles are no problem, the repository management and other artefacts unfortunately are.

You can get the image with **noVNC** and **Chromium** web browser here - [accetto/ubuntu-vnc-xfce-chromium](https://hub.docker.com/r/accetto/ubuntu-vnc-xfce-chromium).

Unfortunatelly **sudo** doesn't play well with the base image, so if you need additional applications, you have to extend the Dockerfile and build your own image.

However, I'll soon release also xubuntu-based images with **noVNC**, that will include  **sudo**.

**Comment by accetto** [comment]
I've just released the first two xubuntu-based images with **noVNC** and **sudo**:

[accetto/xubuntu-vnc-novnc](https://hub.docker.com/r/accetto/xubuntu-vnc-novnc) 
[accetto/xubuntu-vnc-novnc-chromium](https://hub.docker.com/r/accetto/xubuntu-vnc-novnc-chromium)

The firefox image will follow soon.

**Comment by duurent** [comment]
Thanks for these
